FROM rust:1.88-slim AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential pkg-config libssl-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .
RUN echo "=== FILES IN src/ ===" && ls -la src/ && echo "=== FILES IN . ===" && ls -la .

RUN cargo build --release
